apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openrag-openarchiver-connector-https
  labels:
    app.kubernetes.io/name: openrag-openarchiver-connector
    app.kubernetes.io/part-of: openrag
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: openrag-openrag-openarchiver-connector-auth@kubernetescrd,openrag-openrag-openarchiver-connector-headers@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - openrag-openarchiver-connector.ferme-de-pommerieux.fr
  rules:
    - host: openrag-openarchiver-connector.ferme-de-pommerieux.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openrag-openarchiver-connector
                port:
                  name: http
