apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - middleware-auth.yaml
  - middleware-headers.yaml
  - middleware-redirect-https.yaml
  - ingress-http.yaml
  - ingress-https.yaml

configMapGenerator:
  - name: openrag-openarchiver-connector
    files:
      - connector.py

generatorOptions:
  labels:
    app.kubernetes.io/name: openrag-openarchiver-connector
    app.kubernetes.io/part-of: openrag
